### ISSUE TITLE
failed to retrieve bounds for primary keys: failed to retrieve lower bounds for primary keys: Error 1064 (42000)

### ISSUE THREAD

**Issue by kholisrag** [artie-labs/reader#526]
Hi got an error when using the artie-labs/reader with mysql as sources

```yaml
source: mysql
mysql:
  host: dev-server
  port: 3306
  username: artie
  password: xxxxxxxx
  database: ExampleStore
  tables:
    - name: ExampleStore_grade_tracker
    - name: accepted_device

kafka:
  bootstrapServers: artie-kafka-kafka-bootstrap:9092
  topicPrefix: artie_mysql_dev-server_ExampleStore
```

some info:
```bash
 mysql --version
mysql  Ver 14.14 Distrib 5.7.33, for Linux (x86_64) using  EditLine wrapper
```

script for running the `reader`:

```bash
    #!/bin/sh
    set -e
    /reader --config /app/conf/reader-config.yaml
```
